### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by nickcano** [bramp/dissector#1]
I know this is an old project, but I'm wondering if you have any compiled releases and/or quick compilation rundown.

Seems like a great tool for CTF ;)

**Comment by bramp** [comment]
This project is even older than the history makes out. I started this ~5 years ago, and then 2 years ago decided to pushed up to github incase anyone found a use for it.

I don't think I left it in a finished state, but running "mvn" should build it. I'll be up to you to figure out how to use.

However, I recently started a very similar project, https://github.com/bramp/dsector (written in Go), that has the same goals. That might be of interest to you.

**Comment by nickcano** [comment]
Thanks!
